[DEV] Dashboard Self-Hosted

diff --git a/.github/workflows/dashboard_workflow.yml b/.github/workflows/dashboard_workflow.yml
--- a/.github/workflows/dashboard_workflow.yml
+++ b/.github/workflows/dashboard_workflow.yml
@@ -111,18 +111,18 @@ jobs:
   
       - name: Check Python Installation
         run: |
-          python --version || echo "Python not found in PATH"
-  
+          python3 --version || echo "Python not found in PATH"
+      
       - name: Install Python if not present
         run: |
-          if ! command -v python &> /dev/null; then
-            apt-get update && sudo apt-get install -y python3 python3-pip
+          if ! command -v python3 &> /dev/null; then
+            apt-get update && apt-get install -y python3 python3-pip
           fi
-  
-      - name: Ensure pip is in PATH
+      
+      - name: Ensure pip is in PATH for Python3
         run: |
-          if ! command -v pip &> /dev/null; then
-            python -m ensurepip --upgrade
+          if ! command -v pip3 &> /dev/null; then
+            python3 -m ensurepip --upgrade
           fi
   
       - name: Install Streamlit
