Update python-package-conda.yml

diff --git a/.github/workflows/python-package-conda.yml b/.github/workflows/python-package-conda.yml
--- a/.github/workflows/python-package-conda.yml
+++ b/.github/workflows/python-package-conda.yml
@@ -26,7 +26,8 @@ jobs:
       - name: Verify Miniconda Installation
         run: |
           conda --version
-          ls -la ~/miniconda3
+          which conda
+          conda info
 
   install-dependencies:
     needs: install-miniconda
@@ -38,7 +39,7 @@ jobs:
           conda env update --file environment_conda.yml --name dashboard
 
   init-conda:
-    needs: install-dependencies
+    needs: install-dependencies  # Consider if this dependency is necessary
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v4
@@ -55,12 +56,10 @@ jobs:
         run: |
           conda info
       - name: Activate Conda environment
-        shell: bash
+        shell: bash -l {0}
         run: |
-          # Assuming conda.sh is now available after installation
-          source ~/miniconda3/etc/profile.d/conda.sh
+          source $(dirname $(which conda))/../etc/profile.d/conda.sh
           conda activate dashboard
-          
 
   run-dashboard:
     needs: activate-conda
@@ -69,4 +68,4 @@ jobs:
       - uses: actions/checkout@v4
       - name: Run Streamlit Dashboard
         run: |
-          streamlit run main.py --server.headless true
+          streamlit run main.py --server.headless true || echo "Streamlit execution failed with exit code $?"
